version: "3.8"

services:
    app:
        build: ./app
        expose: 
            - 8000
        command: gunicorn superlists.wsgi:application --bind 0.0.0.0:8000
        volumes: 
            - ./app:/usr/src/app
            - static:/usr/src/app/static
        env_file:
            - ./.env.dev

    nginx:
        build: ./nginx
        ports:
            - 8000:80
        volumes:
            - static:/home/app/web/static
        depends_on:
            - app

volumes:
    static:
