version: "3.8"

services:
    app:
        build: ./app
        ports: 
            - 8000:8000
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./app:/usr/src/app
        env_file:
            - ./.env.dev
