version: "3.8"

services:
    app:
        build: ./app
        expose:
            - 8000
        command: gunicorn superlists.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static:/usr/src/app/static
        environment:
            - DEBUG=${DEBUG:-0}
        env_file:
            - .env.prod

    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - static:/home/app/web/static
        depends_on:
            - app

volumes:
    static:
